# Generated by Django 4.1.3 on 2022-12-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unepccc_app', '0005_project_idval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_idVal',
        ),
    ]
