# Generated by Django 4.1.3 on 2022-12-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unepccc_app', '0007_project_expected_cers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='credit_start',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
