# Generated by Django 4.1.3 on 2022-12-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unepccc_app', '0008_project_credit_start_alter_credit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='credit_start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
