# Generated by Django 4.1.3 on 2022-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unepccc_app', '0011_organisation_alter_buyer_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodology',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
